stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    - data/raw/train.csv
    - params.yaml
    outs:
    - data/interim/train.csv
    - data/interim/test.csv

  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - src/features/data_preprocessing.py
    - data/interim/train.csv
    - data/interim/test.csv
    - data/external/chat_words_dictonary.json
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - src/features/feature_engineering.py
    - data/processed/train.csv
    - data/processed/test.csv
    - params.yaml
    outs:
    - data/features/train.csv
    - data/features/test.csv
    - models/vectorizers/bow.joblib

  model_training:
    cmd: python src/models/train_model.py
    deps:
    - src/models/train_model.py
    - data/features/train.csv
    - params.yaml
    outs:
    - models/models/bagging_classifier.joblib

  model_evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - models/models/bagging_classifier.joblib
    - data/features/test.csv

# Generated automatically by DVC only when you are tracking the experiments using dvclive.
artifacts:
  BaggingClassifier:
    path: models/models/bagging_classifier.joblib
    type: model
  train_dataset:
    path: data/features/train.csv
    type: dataset
  test_dataset:
    path: data/features/test.csv
    type: dataset
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
- dvclive/plots/sklearn/precision_recall.json:
    template: simple
    x: recall
    y: precision
    title: Precision-Recall Curve
    x_label: Recall
    y_label: Precision
